#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { createProjectRecord, kitPath, parseArgs, saveProject, writeJson } from './kitbuilder-core.mjs';

const args = parseArgs();
const kitId = args.id;
if (!kitId) {
  console.error('usage: npm run kit:intake -- --id <kit-id> --title "Title" --kind browser-runtime [--idea path]');
  process.exit(1);
}
const title = args.title ?? kitId;
const kind = args.kind ?? 'browser-runtime';
const root = kitPath(kitId);
await fs.mkdir(path.join(root, 'src'), { recursive: true });
await fs.mkdir(path.join(root, 'examples', 'local-basic'), { recursive: true });
await fs.mkdir(path.join(root, 'examples', 'hosted-integration'), { recursive: true });
await fs.mkdir(path.join(root, 'examples', 'live-or-edge'), { recursive: true });

const idea = args.idea ? await fs.readFile(args.idea, 'utf8') : `# ${title}\n\n## Problem\n\nDescribe the problem.\n\n## Intended users\n\nDescribe users.\n\n## Desired behavior\n\nDescribe behavior.\n\n## Rough API\n\nDescribe API.\n`;
await fs.writeFile(path.join(root, 'idea.md'), idea, { flag: 'wx' }).catch(() => {});
for (const [file, heading] of [['README.md', title], ['SCOPE.md', `${title} Scope`], ['API.md', `${title} API`], ['RISK.md', `${title} Risks`]]) {
  await fs.writeFile(path.join(root, file), `# ${heading}\n\nGenerated by KitBuilder02 intake.\n`, { flag: 'wx' }).catch(() => {});
}
await fs.writeFile(path.join(root, 'src', 'index.js'), `export const ${kitId.replace(/(^|-)([a-z])/g, (_, _dash, c) => c.toUpperCase())} = Object.freeze({ id: '${kitId}' });\n`, { flag: 'wx' }).catch(() => {});
await writeJson(path.join(root, 'kit.manifest.json'), {
  id: kitId,
  name: title,
  version: '0.1.0',
  kind,
  status: 'draft',
  entry: 'src/index.js',
  exports: [],
  browserSafe: kind !== 'node-tool' && kind !== 'server-kit',
  nodeSafe: true,
  lifecycle: { currentState: 'idea_captured', stateIndex: 1, totalStates: 20, requiredExamples: 3, completedExamples: 0, promotionReady: false }
});
const project = createProjectRecord({ kitId, manifest: { name: title, kind, status: 'draft' }, owner: args.owner ?? 'agent' });
await saveProject(project, 'Intake created kit scaffold.');
console.log(`Created intake scaffold for ${kitId}.`);
